export const todoActionTypes = {
  FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  TOGGLE_TODO_SUCCESS: 'TOGGLE_TODO_SUCCESS',
  UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
  TODO_ACTION_FAILED: 'TODO_ACTION_FAILED'
};